In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

## Dataset Overview

The dataset used in this project contains financial and demographic information about loan applicants. The goal of the dataset is to support the development of a machine learning model that predicts whether a loan application should be approved or rejected.

The dataset consists of **4269 observations (rows)** and **13 features (columns)**. Each row represents an individual loan application, while the columns represent different attributes related to the applicant’s financial condition, employment status, and asset ownership.

The features include both **numerical variables** (such as income, loan amount, credit score, and asset values) and **categorical variables** (such as education level and employment status).

The **target variable** in this dataset is `loan_status`, which indicates the final decision made by the bank regarding the loan application.

The target variable contains two classes:
- **Approved** – the loan application was accepted.
- **Rejected** – the loan application was denied.

This makes the problem a **binary classification problem**, where the goal of the machine learning model is to predict whether a loan application will be approved or rejected based on the applicant’s financial information.

## Feature Description

The dataset contains several features that describe the financial and personal characteristics of loan applicants.

| Feature | Description |
|-------|-------------|
| loan_id | Unique identifier for each loan application |
| no_of_dependents | Number of dependents financially supported by the applicant |
| education | Applicant's education level (Graduate or Not Graduate) |
| self_employed | Indicates whether the applicant is self-employed |
| income_annum | Annual income of the applicant |
| loan_amount | Total amount of loan requested |
| loan_term | Duration of the loan repayment period |
| cibil_score | Credit score indicating the applicant’s creditworthiness |
| residential_assets_value | Estimated value of residential assets owned |
| commercial_assets_value | Estimated value of commercial assets owned |
| luxury_assets_value | Value of luxury assets owned by the applicant |
| bank_asset_value | Total value of assets held in bank accounts |
| loan_status | Target variable indicating whether the loan was approved or rejected |

## Initial Inspection

To understand the structure of the dataset, an initial inspection was performed. This step helps identify the number of observations, feature types, and potential issues such as missing values or inconsistent data types.

The dataset contains **4269 entries** and **13 columns**. Some variables are categorical (such as education and self_employed), while others are numerical (such as income, loan amount, and asset values).

This step ensures that the dataset structure is appropriate before performing further exploratory data analysis.

In [5]:
df.shape
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

## Exploratory Data Analysis (EDA)

### Statistical Summary

Statistical summaries provide important information about the numerical features in the dataset, including the mean, standard deviation, minimum values, and maximum values.

These statistics help us understand the overall distribution of financial attributes such as income, loan amount, and asset values among loan applicants.

From the statistical summary, we observe that financial attributes such as income and asset values vary significantly across applicants, indicating a diverse financial background among borrowers. The credit score (CIBIL score) is particularly important, as it is expected to have a strong influence on loan approval decisions.

In [6]:
df.describe()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
count,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4.269000e+03,4.269000e+03
mean,2135.000000,2.498712,5.059124e+06,1.513345e+07,10.900445,599.936051,7.472617e+06,4.973155e+06,1.512631e+07,4.976692e+06
std,1232.498479,1.695910,2.806840e+06,9.043363e+06,5.709187,172.430401,6.503637e+06,4.388966e+06,9.103754e+06,3.250185e+06
min,1.000000,0.000000,2.000000e+05,3.000000e+05,2.000000,300.000000,-1.000000e+05,0.000000e+00,3.000000e+05,0.000000e+00
25%,1068.000000,1.000000,2.700000e+06,7.700000e+06,6.000000,453.000000,2.200000e+06,1.300000e+06,7.500000e+06,2.300000e+06
50%,2135.000000,3.000000,5.100000e+06,1.450000e+07,10.000000,600.000000,5.600000e+06,3.700000e+06,1.460000e+07,4.600000e+06
75%,3202.000000,4.000000,7.500000e+06,2.150000e+07,16.000000,748.000000,1.130000e+07,7.600000e+06,2.170000e+07,7.100000e+06
max,4269.000000,5.000000,9.900000e+06,3.950000e+07,20.000000,900.000000,2.910000e+07,1.940000e+07,3.920000e+07,1.470000e+07

## Correlation Analysis

Correlation analysis is used to measure the relationship between numerical features in the dataset. It helps identify which variables may have stronger relationships with each other and which features may influence the target variable.

Financial attributes such as income, loan amount, and asset values may show positive correlations, as applicants with higher income levels often possess more assets. The credit score is expected to have a strong relationship with the loan approval decision, since financial institutions typically rely on credit history to evaluate loan eligibility.

Understanding these correlations helps in selecting relevant features for building the machine learning model in later stages of the project.

In [7]:
corr_matrix = df.corr(numeric_only=True)
corr_matrix

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
loan_id,1.000000,0.005326,0.012592,0.008170,0.009809,0.016323,0.020936,0.018595,-0.000862,0.010765
no_of_dependents,0.005326,1.000000,0.007266,-0.003366,-0.020111,-0.009998,0.007376,-0.001531,0.002817,0.011163
income_annum,0.012592,0.007266,1.000000,0.927470,0.011488,-0.023034,0.636841,0.640328,0.929145,0.851093
loan_amount,0.008170,-0.003366,0.927470,1.000000,0.008437,-0.017035,0.594596,0.603188,0.860914,0.788122
loan_term,0.009809,-0.020111,0.011488,0.008437,1.000000,0.007810,0.008016,-0.005478,0.012490,0.017177
cibil_score,0.016323,-0.009998,-0.023034,-0.017035,0.007810,1.000000,-0.019947,-0.003769,-0.028618,-0.015478
residential_assets_value,0.020936,0.007376,0.636841,0.594596,0.008016,-0.019947,1.000000,0.414786,0.590932,0.527418
commercial_assets_value,0.018595,-0.001531,0.640328,0.603188,-0.005478,-0.003769,0.414786,1.000000,0.591128,0.548576
luxury_assets_value,-0.000862,0.002817,0.929145,0.860914,0.012490,-0.028618,0.590932,0.591128,1.000000,0.788517
bank_asset_value,0.010765,0.011163,0.851093,0.788122,0.017177,-0.015478,0.527418,0.548576,0.788517,1.000000

## Key Insights

Based on the exploratory data analysis, several important insights can be observed:

1. The dataset contains a large number of loan applications (4269), providing sufficient data for training machine learning models.

2. The dataset includes a mix of categorical and numerical features that describe the applicant’s financial situation, employment status, and asset ownership.

3. Financial attributes such as income, loan amount, and asset values show significant variation among applicants.

4. Credit score (CIBIL score) is expected to be one of the most influential factors in determining loan approval.

5. The dataset is structured and suitable for supervised machine learning since it includes a clear target variable (`loan_status`) with two classes: Approved and Rejected.